name: Windows

permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            autoconf
            automake
            libtool
            make
            pkg-config
            unzip
          pacboy: >-
            cairo:p
            freetype:p
            gcc:p
            gettext:p
            gtk3:p
            libgsf:p
            librsvg:p
            libxslt:p
            openssl:p
            ntldd:p

      - name: install_extra
        run: |
          libofx_version="0.9.15"
          libgoffice_version="2019.10.16-19"

          git_src="https://github.com/xfred81"
          bits="64bit"
          MSYSTEM="MINGW64"

          pwd
          cd /
          wget -m --no-verbose -O /libofx.zip "$git_src/libofx/releases/download/$libofx_version/libofx_$MSYSTEM.zip"
          unzip /libofx.zip

          wget -m --no-verbose -O /goffice.zip "$git_src/goffice/releases/download/v-$libgoffice_version/goffice-$bits-$libgoffice_version-archive.zip"
          unzip /goffice.zip

          wget -O /nsis.zip 'https://downloads.sourceforge.net/project/nsis/NSIS 3/3.10/nsis-3.10.zip'
          unzip nsis.zip

      - uses: actions/checkout@v4

      - name: compile
        run: |
          ./autogen.sh

          export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/tmp/inst/lib/pkgconfig

          ./github-actions/build.sh \
            --with-goffice \
            --with-openssl \
            --with-ofx \
            --prefix /c/projects/grisbi-inst

          time make --jobs=4
          time make install

          /nsis-3.10/makensis.exe share/grisbi.nsi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: D:\a\grisbi\grisbi\share\*.exe
